/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class MicroSearch {
  constructor()
  upsertSimple(content: string): string
  upsertLog(content: string, level?: string | undefined | null, service?: string | undefined | null): string
  query(query: string): Array<string>
  queryContent(query: string): Array<string>
}
