name: Build Native Modules

on:
  push:
    branches: [ main ]
  release:
    types: [ created ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            arch: x64
            
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            arch: arm64
            
          - os: macos-latest
            target: x86_64-apple-darwin
            arch: x64
            
          - os: macos-latest
            target: aarch64-apple-darwin
            arch: arm64
            
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            arch: x64

    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build native module
        run: npm run build -- --target ${{ matrix.target }}
        
      - name: Test (Linux x64 only)
        if: matrix.target == 'x86_64-unknown-linux-gnu'
        run: npm test
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bindings-${{ matrix.target }}
          path: "*.node"
          
  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'release'
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
          
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          
      - name: Move binaries to root
        run: |
          cp artifacts/bindings-*/*.node ./
          ls -la *.node
          
      - name: Install dependencies
        run: npm ci
        
      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
